apiVersion: apps/v1
kind: Deployment
metadata:
  name: gigorbit-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gigorbit-frontend
  template:
    metadata:
      labels:
        app: gigorbit-frontend
    spec:
      containers:
        - name: gigorbit-frontend
          image: REPLACE_WITH_IMAGE/gigorbit-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gigorbit-frontend
spec:
  type: ClusterIP
  selector:
    app: gigorbit-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000