apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
    spec:
      containers:
        - name: job-service
          image: REPLACE_WITH_IMAGE/job-service:latest
          env:
            - name: JOB_DB
              value: "/data/jobs.db"
          volumeMounts:
            - name: job-data
              mountPath: /data
          ports:
            - containerPort: 5002
      volumes:
        - name: job-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: job-service
spec:
  selector:
    app: job-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002